POST http://localhost:8080/register
content-type: application/json

{
    "username": "test",
    "email": "victor.machado.perez@gmail.com",
    "password": "1234"
}

###
POST http://localhost:8080/login
content-type: application/json

{
    "username": "test",
    "password": "1234"
}
###
POST http://localhost:8080/login
content-type: application/json

{
    "email": "victor.machado.perez@gmail.com",
    "password": "1234"
}
###

GET http://localhost:8080/