### GET SPACES from test

GET http://localhost:8080/spaces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE4MzI3OWU1YTQ2NGQ2N2EyODY4MTEiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2ODg3NTYzODV9.clNUeSoRt0xuiqPCMa8ETI8J2nQ7vfQc1iIlE8JH9DA

### GET SPACES from victor

GET http://localhost:8080/spaces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE4MzI3Y2U1YTQ2NGQ2N2EyODY4MTQiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY4ODc1NjQyMX0.3ZReab4YyWcHJ7Q_-3pHQ8YeUS6f5gTHk3o3Iv-Dtk0

###############################################################################

### GET ACTIVITIES by test

GET http://localhost:8080/spaces/62fd877c626901c8001008c5/activities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE4MzI3OWU1YTQ2NGQ2N2EyODY4MTEiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2ODg3NTYzODV9.clNUeSoRt0xuiqPCMa8ETI8J2nQ7vfQc1iIlE8JH9DA

### GET ACTIVITIES by victor

GET http://localhost:8080/spaces/62fd877c626901c8001008c5/activities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE4MzI3Y2U1YTQ2NGQ2N2EyODY4MTQiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY4ODc1NjQyMX0.3ZReab4YyWcHJ7Q_-3pHQ8YeUS6f5gTHk3o3Iv-Dtk0

###############################################################################

### CREATE ACTIVITY by test

POST http://localhost:8080/spaces/62fd877c626901c8001008c5/activities
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE4MzI3OWU1YTQ2NGQ2N2EyODY4MTEiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2ODg3NTYzODV9.clNUeSoRt0xuiqPCMa8ETI8J2nQ7vfQc1iIlE8JH9DA

{
    "taskname": "conga2",
    "points": 2,
    "taskId": "62fd9012022121f447dcb1fe"
}
