### GET SPACES

GET http://localhost:8080/spaces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmY2NDdhZjlkZDAxOTI0MTgzMmZmNjkiLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InZpY3Rvci5tYWNoYWRvLnBlcmV6QGdtYWlsLmNvbSIsImlhdCI6MTY2MDMzMDk1OX0.DLGtwivmKUi6xslA-g9HFOEcTGUOlNnjknPvASYmtoQ

### CREATE SPACE

POST http://localhost:8080/spaces
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmY2NDdhZjlkZDAxOTI0MTgzMmZmNjkiLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InZpY3Rvci5tYWNoYWRvLnBlcmV6QGdtYWlsLmNvbSIsImlhdCI6MTY2MDMzMDk1OX0.DLGtwivmKUi6xslA-g9HFOEcTGUOlNnjknPvASYmtoQ

{
    "spacename": "space1"
}

### DELETE SPACE test

DELETE  http://localhost:8080/spaces/62f95128e278d3a657228b47
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmY2NDdhZjlkZDAxOTI0MTgzMmZmNjkiLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InZpY3Rvci5tYWNoYWRvLnBlcmV6QGdtYWlsLmNvbSIsImlhdCI6MTY2MDMzMDk1OX0.DLGtwivmKUi6xslA-g9HFOEcTGUOlNnjknPvASYmtoQ

### DELETE SPACE victor

DELETE  http://localhost:8080/spaces/62f95128e278d3a657228b47
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmY4MWQ3MzNjNGQ1ZjNlNDA2NmI3M2MiLCJ1c2VybmFtZSI6InZpY3RvciIsImVtYWlsIjoidmljdG9yQGdtYWlsLmNvbSIsImlhdCI6MTY2MDQyNzY1OX0.MW4D8bd9lDX1yDMtXYiABKJEW3xtUzBrBX4hPxrCMqY

### JOIN SPACE victor

PUT http://localhost:8080/spaces/62f95128e278d3a657228b47/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmY4MWQ3MzNjNGQ1ZjNlNDA2NmI3M2MiLCJ1c2VybmFtZSI6InZpY3RvciIsImVtYWlsIjoidmljdG9yQGdtYWlsLmNvbSIsImlhdCI6MTY2MDQyNzY1OX0.MW4D8bd9lDX1yDMtXYiABKJEW3xtUzBrBX4hPxrCMqY

### LEAVE SPACE victor

PUT http://localhost:8080/spaces/62f95128e278d3a657228b47/leave
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmY4MWQ3MzNjNGQ1ZjNlNDA2NmI3M2MiLCJ1c2VybmFtZSI6InZpY3RvciIsImVtYWlsIjoidmljdG9yQGdtYWlsLmNvbSIsImlhdCI6MTY2MDQyNzY1OX0.MW4D8bd9lDX1yDMtXYiABKJEW3xtUzBrBX4hPxrCMqY

{
    "userId": "62f647af9dd019241832ff69"
}
### JOIN SPACE test

PUT http://localhost:8080/spaces/62f95128e278d3a657228b47/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmY2NDdhZjlkZDAxOTI0MTgzMmZmNjkiLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InZpY3Rvci5tYWNoYWRvLnBlcmV6QGdtYWlsLmNvbSIsImlhdCI6MTY2MDMzMDk1OX0.DLGtwivmKUi6xslA-g9HFOEcTGUOlNnjknPvASYmtoQ

### LEAVE SPACE test

PUT http://localhost:8080/spaces/62f95128e278d3a657228b47/leave
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmY2NDdhZjlkZDAxOTI0MTgzMmZmNjkiLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InZpY3Rvci5tYWNoYWRvLnBlcmV6QGdtYWlsLmNvbSIsImlhdCI6MTY2MDMzMDk1OX0.DLGtwivmKUi6xslA-g9HFOEcTGUOlNnjknPvASYmtoQ

{
    "userId": "62f647af9dd019241832ff69"
}
### ADD ADMIN SPACE test

PUT  http://localhost:8080/spaces/62f95128e278d3a657228b47/addAdmin
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmY2NDdhZjlkZDAxOTI0MTgzMmZmNjkiLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InZpY3Rvci5tYWNoYWRvLnBlcmV6QGdtYWlsLmNvbSIsImlhdCI6MTY2MDMzMDk1OX0.DLGtwivmKUi6xslA-g9HFOEcTGUOlNnjknPvASYmtoQ

{
    "username": "victor",
    "userId": "62f81d733c4d5f3e4066b73c"
}

### ADD ADMIN SPACE victor

PUT  http://localhost:8080/spaces/62f95128e278d3a657228b47/addAdmin
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmY4MWQ3MzNjNGQ1ZjNlNDA2NmI3M2MiLCJ1c2VybmFtZSI6InZpY3RvciIsImVtYWlsIjoidmljdG9yQGdtYWlsLmNvbSIsImlhdCI6MTY2MDQyNzY1OX0.MW4D8bd9lDX1yDMtXYiABKJEW3xtUzBrBX4hPxrCMqY

{
    "username": "victor",
    "userId": "62f81d733c4d5f3e4066b73c"
}

### DELETE ADMIN SPACE test

PUT  http://localhost:8080/spaces/62f95128e278d3a657228b47/deleteAdmin
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmY2NDdhZjlkZDAxOTI0MTgzMmZmNjkiLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InZpY3Rvci5tYWNoYWRvLnBlcmV6QGdtYWlsLmNvbSIsImlhdCI6MTY2MDMzMDk1OX0.DLGtwivmKUi6xslA-g9HFOEcTGUOlNnjknPvASYmtoQ

{
    "username": "victor",
    "userId": "62f81d733c4d5f3e4066b73c"
}

### DELETE ADMIN SPACE test

PUT  http://localhost:8080/spaces/62f95128e278d3a657228b47/deleteAdmin
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmY2NDdhZjlkZDAxOTI0MTgzMmZmNjkiLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InZpY3Rvci5tYWNoYWRvLnBlcmV6QGdtYWlsLmNvbSIsImlhdCI6MTY2MDMzMDk1OX0.DLGtwivmKUi6xslA-g9HFOEcTGUOlNnjknPvASYmtoQ

{
    "username": "test",
    "userId": "62f647af9dd019241832ff69"
}

### DELETE ADMIN SPACE victor

PUT  http://localhost:8080/spaces/62f95128e278d3a657228b47/deleteAdmin
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmY4MWQ3MzNjNGQ1ZjNlNDA2NmI3M2MiLCJ1c2VybmFtZSI6InZpY3RvciIsImVtYWlsIjoidmljdG9yQGdtYWlsLmNvbSIsImlhdCI6MTY2MDQyNzY1OX0.MW4D8bd9lDX1yDMtXYiABKJEW3xtUzBrBX4hPxrCMqY

{
    "username": "victor",
    "userId": "62f81d733c4d5f3e4066b73c"
}
