### GET SPACES from test

GET http://localhost:8080/spaces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc3YzYyNjkwMWM4MDAxMDA4YzUiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NjA3ODI0NzF9.S_wP0EXZW-AQcGGAdBuOipsb414KycL9-i7Jv4jTGyM

### GET SPACES from victor

GET http://localhost:8080/spaces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc4MTYyNjkwMWM4MDAxMDA4YzkiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY2MDc4MjUwMX0.XSU3YUfhEJTTz8DxB4oxTr4YVew8Y0WTp5nLNdY2LIw

###############################################################################
###############################################################################

### CREATE SPACE by test

POST http://localhost:8080/spaces
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc3YzYyNjkwMWM4MDAxMDA4YzUiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NjA3ODI0NzF9.S_wP0EXZW-AQcGGAdBuOipsb414KycL9-i7Jv4jTGyM

{
    "spacename": "space by test",
    "color": "#ff0000"
}

### CREATE SPACE by victor

POST http://localhost:8080/spaces
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc4MTYyNjkwMWM4MDAxMDA4YzkiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY2MDc4MjUwMX0.XSU3YUfhEJTTz8DxB4oxTr4YVew8Y0WTp5nLNdY2LIw

{
    "spacename": "space by victor"
}

###############################################################################
###############################################################################

### DELETE SPACE by test

DELETE  http://localhost:8080/spaces/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc3YzYyNjkwMWM4MDAxMDA4YzUiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NjA3ODI0NzF9.S_wP0EXZW-AQcGGAdBuOipsb414KycL9-i7Jv4jTGyM

{
    "spaceId": "62fe22b00bc1b7df53213cdc"
}

### DELETE SPACE by victor

DELETE  http://localhost:8080/spaces/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc4MTYyNjkwMWM4MDAxMDA4YzkiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY2MDc4MjUwMX0.XSU3YUfhEJTTz8DxB4oxTr4YVew8Y0WTp5nLNdY2LIw

{
    "spaceId": "62fe22b00bc1b7df53213cdc"
}
###############################################################################
###############################################################################

### Get Users by victor

DELETE  http://localhost:8080/spaces/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc4MTYyNjkwMWM4MDAxMDA4YzkiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY2MDc4MjUwMX0.XSU3YUfhEJTTz8DxB4oxTr4YVew8Y0WTp5nLNdY2LIw

{
    "spaceId": "62fe22b00bc1b7df53213cdc"
}
###############################################################################
###############################################################################

### JOIN SPACE admin:test joining: test

PUT http://localhost:8080/spaces/62fe22b00bc1b7df53213cdc/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc3YzYyNjkwMWM4MDAxMDA4YzUiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NjA3ODI0NzF9.S_wP0EXZW-AQcGGAdBuOipsb414KycL9-i7Jv4jTGyM

{
    "username": "test",
    "_id": "62fd877c626901c8001008c5",
    "color": "#ff0000"
}

### JOIN SPACE admin:test joining: victor

PUT http://localhost:8080/spaces/62fe22b00bc1b7df53213cdc/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc3YzYyNjkwMWM4MDAxMDA4YzUiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NjA3ODI0NzF9.S_wP0EXZW-AQcGGAdBuOipsb414KycL9-i7Jv4jTGyM

{
    "username": "victor",
    "_id": "62fd8781626901c8001008c9",
    "color": "#ff0000"
}

### JOIN SPACE admin: victor joining: victor

PUT http://localhost:8080/spaces/62fe22b00bc1b7df53213cdc/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc4MTYyNjkwMWM4MDAxMDA4YzkiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY2MDc4MjUwMX0.XSU3YUfhEJTTz8DxB4oxTr4YVew8Y0WTp5nLNdY2LIw

{
    "username": "victor",
    "_id": "62fd8781626901c8001008c9",
    "color": "#ff0000"
}

### JOIN SPACE admin: victor joining: test

PUT http://localhost:8080/spaces/62fe22b00bc1b7df53213cdc/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc4MTYyNjkwMWM4MDAxMDA4YzkiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY2MDc4MjUwMX0.XSU3YUfhEJTTz8DxB4oxTr4YVew8Y0WTp5nLNdY2LIw

{
    "username": "test",
    "_id": "62fd877c626901c8001008c5",
    "color": "#ff0000"
}

###############################################################################
###############################################################################

### LEAVE SPACE admin:test leaving: test

DELETE http://localhost:8080/spaces/62fe22b00bc1b7df53213cdc/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc3YzYyNjkwMWM4MDAxMDA4YzUiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NjA3ODI0NzF9.S_wP0EXZW-AQcGGAdBuOipsb414KycL9-i7Jv4jTGyM

{
    "username": "test",
    "_id": "62fd877c626901c8001008c5"
}

### LEAVE SPACE admin:test leaving: victor

DELETE http://localhost:8080/spaces/62fe22b00bc1b7df53213cdc/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc3YzYyNjkwMWM4MDAxMDA4YzUiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NjA3ODI0NzF9.S_wP0EXZW-AQcGGAdBuOipsb414KycL9-i7Jv4jTGyM

{
    "username": "victor",
    "_id": "62fd8781626901c8001008c9"
}

### LEAVE SPACE admin:victor leaving test

DELETE http://localhost:8080/spaces/62fe22b00bc1b7df53213cdc/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc4MTYyNjkwMWM4MDAxMDA4YzkiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY2MDc4MjUwMX0.XSU3YUfhEJTTz8DxB4oxTr4YVew8Y0WTp5nLNdY2LIw

{
    "username": "test",
    "_id": "62fd877c626901c8001008c5"
}

### LEAVE SPACE admin:victor leaving: victor

DELETE http://localhost:8080/spaces/62fe22b00bc1b7df53213cdc/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc4MTYyNjkwMWM4MDAxMDA4YzkiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY2MDc4MjUwMX0.XSU3YUfhEJTTz8DxB4oxTr4YVew8Y0WTp5nLNdY2LIw

{
    "username": "victor",
    "_id": "62fd8781626901c8001008c9"
}

###############################################################################
###############################################################################

### ADD ADMIN SPACE admin:test adding:victor

POST  http://localhost:8080/spaces/62fe22b00bc1b7df53213cdc/admins
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc3YzYyNjkwMWM4MDAxMDA4YzUiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NjA3ODI0NzF9.S_wP0EXZW-AQcGGAdBuOipsb414KycL9-i7Jv4jTGyM

{
    "username": "victor",
    "_id": "62fd8781626901c8001008c9"
}

### ADD ADMIN SPACE admin:victor adding:victor

POST  http://localhost:8080/spaces/62fe22b00bc1b7df53213cdc/admins
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc4MTYyNjkwMWM4MDAxMDA4YzkiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY2MDc4MjUwMX0.XSU3YUfhEJTTz8DxB4oxTr4YVew8Y0WTp5nLNdY2LIw

{
    "username": "victor",
    "_id": "62fd8781626901c8001008c9"
}

### ADD ADMIN SPACE admin:victor adding:test

POST  http://localhost:8080/spaces/62fe22b00bc1b7df53213cdc/admins
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc4MTYyNjkwMWM4MDAxMDA4YzkiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY2MDc4MjUwMX0.XSU3YUfhEJTTz8DxB4oxTr4YVew8Y0WTp5nLNdY2LIw

{
    "username": "test",
    "_id": "62fd877c626901c8001008c5"
}

###############################################################################
###############################################################################

### DELETE ADMIN SPACE admin:test deleting:test

DELETE  http://localhost:8080/spaces/62fe22b00bc1b7df53213cdc/admins
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc3YzYyNjkwMWM4MDAxMDA4YzUiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NjA3ODI0NzF9.S_wP0EXZW-AQcGGAdBuOipsb414KycL9-i7Jv4jTGyM

{
    "username": "test",
    "_id": "62fd877c626901c8001008c5"
}

### DELETE ADMIN SPACE admin:test deleting:victor

DELETE  http://localhost:8080/spaces/62fe22b00bc1b7df53213cdc/admins
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc3YzYyNjkwMWM4MDAxMDA4YzUiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NjA3ODI0NzF9.S_wP0EXZW-AQcGGAdBuOipsb414KycL9-i7Jv4jTGyM

{
    "username": "victor",
    "_id": "62fd8781626901c8001008c9"
}

### DELETE ADMIN SPACE admin:victor deleting: victor

DELETE  http://localhost:8080/spaces/62fe22b00bc1b7df53213cdc/admins
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc4MTYyNjkwMWM4MDAxMDA4YzkiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY2MDc4MjUwMX0.XSU3YUfhEJTTz8DxB4oxTr4YVew8Y0WTp5nLNdY2LIw

{
    "username": "victor",
    "_id": "62fd8781626901c8001008c9"
}

### DELETE ADMIN SPACE admin:victor deleting: test

DELETE  http://localhost:8080/spaces/62fe22b00bc1b7df53213cdc/admins
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZkODc4MTYyNjkwMWM4MDAxMDA4YzkiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY2MDc4MjUwMX0.XSU3YUfhEJTTz8DxB4oxTr4YVew8Y0WTp5nLNdY2LIw

{
    "username": "test",
    "_id": "62fd877c626901c8001008c5"
}
