### GET SPACES from test

GET http://localhost:8080/spaces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE4MzI3OWU1YTQ2NGQ2N2EyODY4MTEiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2ODg3NTYzODV9.clNUeSoRt0xuiqPCMa8ETI8J2nQ7vfQc1iIlE8JH9DA

### GET SPACES from victor

GET http://localhost:8080/spaces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE4MzI3Y2U1YTQ2NGQ2N2EyODY4MTQiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY4ODc1NjQyMX0.3ZReab4YyWcHJ7Q_-3pHQ8YeUS6f5gTHk3o3Iv-Dtk0

###############################################################################

### GET TASKS by test

GET http://localhost:8080/spaces/62fd877c626901c8001008c5/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE4MzI3OWU1YTQ2NGQ2N2EyODY4MTEiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2ODg3NTYzODV9.clNUeSoRt0xuiqPCMa8ETI8J2nQ7vfQc1iIlE8JH9DA

### GET TASKS by victor

GET http://localhost:8080/spaces/62fd877c626901c8001008c5/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE4MzI3Y2U1YTQ2NGQ2N2EyODY4MTQiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY4ODc1NjQyMX0.3ZReab4YyWcHJ7Q_-3pHQ8YeUS6f5gTHk3o3Iv-Dtk0

###############################################################################

### CREATE TASK by test

POST http://localhost:8080/spaces/62fd877c626901c8001008c5/tasks
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE4MzI3OWU1YTQ2NGQ2N2EyODY4MTEiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2ODg3NTYzODV9.clNUeSoRt0xuiqPCMa8ETI8J2nQ7vfQc1iIlE8JH9DA

{
    "taskname": "Roomba2",
    "points": 2
}

### CREATE TASK by victor

POST http://localhost:8080/spaces/62fd877c626901c8001008c5/tasks
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE4MzI3Y2U1YTQ2NGQ2N2EyODY4MTQiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY4ODc1NjQyMX0.3ZReab4YyWcHJ7Q_-3pHQ8YeUS6f5gTHk3o3Iv-Dtk0

{
    "taskname": "Roomba",
    "points": 1
}

### DELETE TASK by victor

DELETE http://localhost:8080/spaces/62fd877c626901c8001008c5/tasks/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE4MzI3Y2U1YTQ2NGQ2N2EyODY4MTQiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY4ODc1NjQyMX0.3ZReab4YyWcHJ7Q_-3pHQ8YeUS6f5gTHk3o3Iv-Dtk0

{
    "taskId": "62fd9010022121f447dcb1fb"
}

### UPDATE TASK by victor

PUT http://localhost:8080/spaces/62fd877c626901c8001008c5/tasks/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE4MzI3Y2U1YTQ2NGQ2N2EyODY4MTQiLCJ1c2VybmFtZSI6InZpY3RvciIsImlhdCI6MTY4ODc1NjQyMX0.3ZReab4YyWcHJ7Q_-3pHQ8YeUS6f5gTHk3o3Iv-Dtk0

{
    "taskId": "62fd929e6b93b0cfd862ab55",
    "taskname": "asdf",
    "points": 33
}