### GET USERS from test

GET http://localhost:8080/users/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGE4MzI3OWU1YTQ2NGQ2N2EyODY4MTEiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2ODg3NTYzODV9.clNUeSoRt0xuiqPCMa8ETI8J2nQ7vfQc1iIlE8JH9DA

{
    "search": ""
}

### DELETE test
DELETE http://localhost:8080/users/62ff6beaaa31c5cdb9562045
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmZmNmJlYWFhMzFjNWNkYjk1NjIwNDUiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NjA5MDY1MDN9.QV69S_R0tIHBRDNRSuk07rhglH7qZxC16Zwa-g6Ttxo
